server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8090
#          predicates:
#            - Path= /users/**
#        - id: r1
#          uri: http://localhost:8091
#          predicates:
#            - Path= /logistique/**
#

